//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapMVCPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationID { get; set; }
        public string Title { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ImagePath { get; set; }
        public string Detail { get; set; }
        public Nullable<double> Price { get; set; }
        public string Bed { get; set; }
        public string Wardrobe { get; set; }
        public string Conditioner { get; set; }
        public string Desk { get; set; }
        public string Toilet { get; set; }
        public string Refrigrator { get; set; }
        public string Wifi { get; set; }
    }
}
